const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
const GET_PRODUCT_REQUEST = "GET_PRODUCTS_REQUEST";
const GET_PRODUCT_SUCCESS = "GET_PRODUCTS_SUCCESS";
const GET_PRODUCT_FAIL = "GET_PRODUCTS_FAIL";
const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";
const ADD_TO_CART = "ADD_TO_CART";
const INCREASE = "INCREASE";
const DECREASE = "DECREASE";
const DELETE = "DELETE";
const CLEAR_CART = "CLEAR_CART";

export {
    GET_PRODUCTS_REQUEST,
    GET_PRODUCTS_SUCCESS,
    GET_PRODUCTS_FAIL,
    GET_PRODUCT_REQUEST,
    GET_PRODUCT_SUCCESS,
    GET_PRODUCT_FAIL,
    GET_CATEGORIES_REQUEST,
    GET_CATEGORIES_SUCCESS,
    GET_CATEGORIES_FAIL,
    ADD_TO_CART,
    INCREASE,
    DECREASE,
    DELETE,
    CLEAR_CART,
}